var restaurants = [
	"Tantuni",
	"Cosmic Kitchen",
	"Mr Wok", 
	"The Thai House",
	"The Bridge",
	"Cosmic Kitchen",
	"KuKu",
	"Dunya",
	"The Red Lantern",
	"Honkytonk",
	"Eddystone Inn",
	"Toot",
	"Le Monde",
	"Stavros Greek Taverna",
	"Blues Bar and Grill",
	"Mama Rita's Kitchen",
	"The Ship",
	"Imperial Garden",
	"Greek Soul Kitchen",
	"Everest Spice",
	"The Village Restaurant",
	"Nawroz",
	"Indian Rose",
	"Cornwall Street Fish Bar",
	"Waypoint Bar and Bistro",
	"Lockyers Quay Cookhouse & Pub",
	"The Bottling Plant",
	"Pub on the Hoe",
	"Bamo",
	"The King's Arms",
	"The Dock",
	"Shapla",
	"New Crystal Dragon",
	"Gurkha's Kitchen",
	"The Fishermans Arms",
	"Oishi Sushi",
	"Ocean View Bar and Dining At The Dome",
	"The Colebrook Inn",
	"Turtle Bay",
	"Cafe Bistro 23",
	"The Morley Bar & Eatery",
	"The Treasury",
	"Zeus",
	"Mombay Brasserie",
	"Clovelly Bay Inn",
	"Aleppo",
	"Steve's Brasserie",
	"Pier Masters House",
	"The Catch",
	"New Oriental Tea Room",
	"Platters",
	"Arribas",
	"The Lord High Admiral",
	"Crown and Anchor",
	"The Waterfront",
	"The Cherry Tree",
	"Roy Thai",
	"Barbican Pasta Bar",
	"Ferry House Inn",
	"Acleaf",
	"Bonne Sante",
	"Steak and Omelette",
	"Soul Food Vendor",
	"Lorenzos",
	"Maritimo",
	"Cafe Zambezi",
	"Lipson Tandoori",
	"Lost in Rio",
	"The Hook & Line",
	"Positano",
	"Revolution",
	"The Social",
	"Supha's Street Food Emporium",
	"Barbican Steakhouse",
	"Marco Pierre White Steakhouse Bar and Grill",
	"Yukisan",
	"Quay 33",
	"Asian Noodle Bar",
	"Tilt",
	"1620 Pub & Eatery",
	"Lacky's Balti House",
	"The Fig Tree @ 36",
	"Leandra",
	"Tantuni",
	"The Box",
	"Himalayan Spice",
	"Admiral MacBride",
	"The New Lanterns",
	"Platos",
	"The Harbour Seafood Restaurant",
	"Fletcher's",
	"Wokfusion",
	"Samphire",
	"Eastern Eye Indian Restaurant",
	"Barbican Kitchen",
	"Mamma Mia",
	"Salumi",
	"Meze Grill",
	"The Maritime Inn",
	"Aroma",
	"Artillery Tower",
	"The Boathouse"
]
function newRestaurant() {
	var randomNumber = Math.floor(Math.random() * (restaurants.length));
	document.getElementById('restaurantDisplay').innerHTML = restaurants[randomNumber];
}
